Doctor/Controllers/AdaugarePacientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Doctor.Models;

namespace Doctor.Controllers
{
    public class AdaugarePacientController : Controller
    {
        // GET: AdaugarePacient
        DoctorEntities db = new DoctorEntities();
        public ActionResult Adaugare()
        {
            return View();
        }
        /// <summary>
        /// Obiecte aferente claselor AdPacient si Pacient pentru a putea adauga un pacient
        /// </summary>
        /// <param name="pacient1"></param>
        /// <param name="pacient"></param>
        /// <returns>string</returns>
        [HttpPost]
        public ActionResult Adaugare(AdPacient pacient1,Pacient pacient)
        {
            
            if (ModelState.IsValid)
            {
                pacient.Data = DateTime.Now;
                pacient.MedicPId = (int)Session["ID"];
                db.Pacients.Add(pacient);//adaugam o noua inregistrare in db
                db.SaveChanges();//o salvam
                return RedirectToAction("Index", "Pacients");//dupa care ne intorcem pe pagina principala
            }
            return View(pacient);
           
        }
    }
}

Doctor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Doctor.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Doctor/Controllers/InregistrareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Doctor.Models;
namespace Doctor.Controllers
{
    public class InregistrareController : Controller
    {
        private DoctorEntities db = new DoctorEntities();
        private Inregistrare ob = new Inregistrare();

        public ActionResult Inregistrare()
        {
            return View();
        }
        #region Verificare daca emailul se gaseste in baza de date
        public bool IsEmailExists(string eMail)
        {
            var IsCheck = db.Medics.Where(email => email.Email == eMail).FirstOrDefault();
            return IsCheck != null;
        }
        public ActionResult Index()
        {
            return View();
        }
        #endregion
        /// <summary>
        /// creeam un obiect medic aferent clasei Medic
        /// si facem inregistararea
        /// </summary>
        /// <param name="medic"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inregistrare(Medic medic)
        {

            var IsExists = IsEmailExists(medic.Email);//verificare daca emailul introdus se afla in baza de date
            if (IsExists)//da acesta se afla in baza de date 
            {
                //se afiseaza
                ModelState.AddModelError("EmailExists", "Email Already Exists");
                return View();
                
            }
            else
            if (ModelState.IsValid)
            {
                db.Medics.Add(medic);//adaugam o noua inregistrare in db
                db.SaveChanges();//o salvam
                return RedirectToAction("Index", "Home");//dupa care ne intorcem pe pagina principala
            }
            
                return View(medic);
            
        }
        


       
       
         
       
        #region User Login
        public ActionResult Conectare()
        {
            return View();
        }
        /// <summary>
        /// adaugam un obiect con aferent clasei conectare din Models
        /// si un obiect medic aferent clasei Medic pentru a putea aceesa datele din clasa
        /// </summary>
        /// <param name="con"></param>
        /// <param name="medic"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Conectare(Conectare con, Medic medic)
        {
            var _passWord = medic.Parola;
            bool Isvalid = db.Medics.Any(x => x.Email == con.Email  &&
            x.Parola == _passWord);
            if (Isvalid)
            {

                int timeout = con.Rememberme ? 60 : 5; // Timeout in minutes, 60 = 1 hour.  
                var ticket = new FormsAuthenticationTicket(con.Email, false, timeout);
                string encrypted = FormsAuthentication.Encrypt(ticket);
                
                var userDetail = db.Medics.Where(x => x.Email == con.Email  && x.Parola == _passWord).FirstOrDefault();

                FormsAuthentication.SetAuthCookie(medic.ID.ToString(), false);
                Session["ID"] = userDetail.ID;
                Session["Prenume"] = userDetail.Prenume;



                return RedirectToAction("Index", "Home");

            }
            else
            {
                ModelState.AddModelError("", "Invalid Information... Please try again!");
            }
            return View();
        }
        #endregion
        [HttpGet]
        public ActionResult Deconectare()
        {
            Session.Remove("Prenume");
            Session.Remove("ID");
            return RedirectToAction("Index","Home");
        }




    }
}




    

Doctor/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Doctor/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Doctor/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<link rel="stylesheet" href="~/Style/css/indexhome.css" />*@
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">


        <div class="item active">
            <img src="~/Style/images/1.jpg" alt="ASP.NET" class="image" />

            <div class="carousel-caption" role="option">
                @if (Session["ID"] == null)
                {
                    @Html.ActionLink("Vezi lista pacienti", "Conectare", "Inregistrare")



                    @Html.ActionLink("Adauga un pacient", "Conectare", "Inregistrare")
                }
                else
                {
                    @Html.ActionLink("Vezi lista pacienti", "Index", "Pacients")



                    @Html.ActionLink("Adauga un pacient", "Adaugare", "AdaugarePacient")
                }


            </div>
        </div>
        <div class="item">
            <img src="~/Style/images/2.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">

                @if (Session["ID"] == null)
                {
                    @Html.ActionLink("Vezi lista pacienti", "Conectare", "Inregistrare")



                    @Html.ActionLink("Adauga un pacient", "Conectare", "Inregistrare")
                }
                else
                {
                    @Html.ActionLink("Vezi lista pacienti", "Index", "Pacients")



                    @Html.ActionLink("Adauga un pacient", "Adaugare", "AdaugarePacient")
                }

            </div>
        </div>
        <div class="item">
            <img src="~/Style/images/3.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                @if (Session["ID"] == null)
                {
                    @Html.ActionLink("Vezi lista pacienti", "Conectare", "Inregistrare")



                    @Html.ActionLink("Adauga un pacient", "Conectare", "Inregistrare")
                }
                else
                {
                    @Html.ActionLink("Vezi lista pacienti", "Index", "Pacients")



                    @Html.ActionLink("Adauga un pacient", "Adaugare", "AdaugarePacient")
                }
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<style>

    #myCarousel {
        height: 100vh;
        background-size: cover;
        background-position: center;
    }
    
    .item {
        height: 100vh;
        background-size: cover;
        background-position: center;
    }

    .image {
        background-size: cover;
    }

    .carousel-caption {
        margin-bottom: 15%; /*200px;*/
        color:aquamarine;
    }

        .carousel-caption a {
            text-decoration: none;
            padding: 2%; /*15*/
            background-color: lawngreen;
            color: black;
            border-radius: 5px 5px 5px 5px;
            border: 1px solid black;
            margin: 2px;
            
        }

            .carousel-caption a:hover {
                border: 1px solid black;
            }

    .item active {
        width: 100%;
    }

    .item img {
        width: 100%;
    }
</style>