Doctor/Models/Pacient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doctor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.Consultaties = new HashSet<Consultatie>();
        }
    
        public int ID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string CNP { get; set; }
        public string Email { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string NrCard { get; set; }
        public string Asigurarea { get; set; }
        public string Alergii { get; set; }
        public string Antecedente_heredocolaterale { get; set; }
        public string Antecedente_personale_patologice { get; set; }
        public string Antecedente_personale_fiziologice { get; set; }
        public string Meseria { get; set; }
        public string LocMunca { get; set; }
        public Nullable<bool> Fumator { get; set; }
        public Nullable<bool> Elev { get; set; }
        public Nullable<bool> Student { get; set; }
        public Nullable<double> Greutate { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Varsta { get; set; }
        public Nullable<System.DateTime> DataNastere { get; set; }
        public Nullable<int> MedicPId { get; set; }
        public string Vaccinuri { get; set; }
        public Nullable<int> Nr_sarcini { get; set; }
        public Nullable<int> Nr_avorturi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultatie> Consultaties { get; set; }
        public virtual Medic Medic { get; set; }
    }
}

Doctor/Controllers/AdaugarePacientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Doctor.Models;

namespace Doctor.Controllers
{
    public class AdaugarePacientController : Controller
    {
        // GET: AdaugarePacient
        DoctorEntities db = new DoctorEntities();
        public ActionResult Adaugare()
        {
            return View();
        }
        /// <summary>
        /// Obiecte aferente claselor AdPacient si Pacient pentru a putea adauga un pacient
        /// </summary>
        /// <param name="pacient1"></param>
        /// <param name="pacient"></param>
        /// <returns>string</returns>
        [HttpPost]
        public ActionResult Adaugare(AdPacient pacient1,Pacient pacient)
        {
            
            if (ModelState.IsValid)
            {
                pacient.Data = DateTime.Now;
                pacient.MedicPId = (int)Session["ID"];
                db.Pacients.Add(pacient);//adaugam o noua inregistrare in db
                db.SaveChanges();//o salvam
                return RedirectToAction("Index", "Pacients");//dupa care ne intorcem pe pagina principala
            }
            return View(pacient);
           
        }
    }
}

Doctor/Controllers/ConsultatiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Doctor.Models;

namespace Doctor.Controllers
{
    public class ConsultatiesController : Controller
    {
        private DoctorEntities db = new DoctorEntities();

        // GET: Consultaties
        public ActionResult Index1(int consultatieid)
        {
            // var consultaties = db.Consultaties.Include(c => c.Medic).Include(c => c.Pacient);
            List<Consultatie> consultatie = db.Consultaties.Include(a => a.Pacient).Include(a => a.Medic).ToList();
          
            //return View(consultaties.ToList());
            if(consultatieid!=0)
            {
                consultatie=consultatie.Where(a => a.PacientId==consultatieid).ToList();
            }
            return View(consultatie.ToList());
        }

        // GET: Consultaties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultatie consultatie = db.Consultaties.Find(id);
            if (consultatie == null)
            {
                return HttpNotFound();
            }
            return View(consultatie);
        }

        // GET: Consultaties/Create
        public ActionResult Create()
        {
            ViewBag.MediCId = new SelectList(db.Medics, "ID", "Nume");
            ViewBag.PacientId = new SelectList(db.Pacients, "ID", "Nume");
            return View();
        }

        // POST: Consultaties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PacientId,MediCId,Data,Temperatura,Greutate,Talie,Inaltime,IMC,RezultateAnalize,Diagnostic,Tratament,Observatii")] Consultatie consultatie,int consultatieid)
        {
            if (ModelState.IsValid)
            {
                Pacient pacient = db.Pacients.Find(consultatieid);

                db.Consultaties.Add(consultatie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MediCId = new SelectList(db.Medics, "ID", "Nume", consultatie.MediCId);
            ViewBag.PacientId = new SelectList(db.Pacients, "ID", "Nume", consultatie.PacientId);
            return View(consultatie);
        }

        // GET: Consultaties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultatie consultatie = db.Consultaties.Find(id);
            if (consultatie == null)
            {
                return HttpNotFound();
            }
            ViewBag.MediCId = new SelectList(db.Medics, "ID", "Nume", consultatie.MediCId);
            ViewBag.PacientId = new SelectList(db.Pacients, "ID", "Nume", consultatie.PacientId);
            return View(consultatie);
        }

        // POST: Consultaties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PacientId,MediCId,Data,Temperatura,Greutate,Talie,Inaltime,IMC,RezultateAnalize,Diagnostic,Tratament,Observatii")] Consultatie consultatie)
        {
            if (ModelState.IsValid)
            {
                consultatie.Data = DateTime.Now;
                db.Entry(consultatie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index","Pacients");
            }
            ViewBag.MediCId = new SelectList(db.Medics, "ID", "Nume", consultatie.MediCId);
            ViewBag.PacientId = new SelectList(db.Pacients, "ID", "Nume", consultatie.PacientId);
            return View(consultatie);
        }

        // GET: Consultaties/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultatie consultatie = db.Consultaties.Find(id);
            if (consultatie == null)
            {
                return HttpNotFound();
            }
            return View(consultatie);
        }

        // POST: Consultaties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consultatie consultatie = db.Consultaties.Find(id);
            db.Consultaties.Remove(consultatie);
            db.SaveChanges();
            
            return RedirectToAction("Index","Pacients");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Doctor/Controllers/PacientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Doctor.Models;
using static System.Net.WebRequestMethods;

namespace Doctor.Controllers
{
    public class PacientsController : Controller
    {
        private DoctorEntities db = new DoctorEntities();

        // GET: Pacients
        /// <summary>
        /// pentru searchbox sunt folosite doua variabile una pentru cautare se tip streeng -searching
        /// si una pentru verificare de tip bool -myRequestsOnly
        /// </summary>
        /// <param name="searching"></param>
        /// <param name="myRequestsOnly"></param>
        /// <returns></returns>
        public ActionResult Index(string searching, bool myRequestsOnly = false)
        {
            //var pacients = db.Pacients.Include(p => p.Medic);

            //List<Pacient> result = db.Pacients.Where(r => r.CNP.Contains(searching) || searching == null).ToList();

            //return View(pacients.ToList());
            List<Pacient> result = db.Pacients.Where(r => r.CNP.Contains(searching) || searching == null).ToList();
            Pacient pacient = new Pacient();
            if (myRequestsOnly == true)
            {
                result = result.Where(r => r.MedicPId == (int)Session["ID"]).ToList();
            }
            return View(result);
        }
        /// <summary>
        /// primeste id-ul de referinta a pacientului si trimite catre view informatiile de afisare
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Pacients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacient pacient = db.Pacients.Find(id);
            if (pacient == null)
            {
                return HttpNotFound();
            }
            return View(pacient);
        }

        // GET: Pacients/Create
      
        public ActionResult Create()
        {
            ViewBag.MedicPId = new SelectList(db.Medics, "ID", "Nume");
            return View();
        }

        // POST: Pacients/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nume,Prenume,Data,CNP,Email,Adresa,Telefon,NrCard,Asigurarea,Alergii,Antecedente_heredocolaterale,Antecedente_personale_patologice,Antecedente_personale_fiziologice,Meseria,LocMunca,Fumator,Elev,Student,Greutate,Sex,Varsta,DataNastere,MedicPId,Vaccinuri,Nr_sarcini,Nr_avorturi")] Pacient pacient,Medic medic)
        {
            if (ModelState.IsValid)
            {
                //Pacient p = new Pacient();
               
                // pacient.ID = medic.ID;
                //pacient.ID = (int)Session["ID"];
                pacient.MedicPId = (int)Session["ID"];
                pacient.Data = DateTime.Now;
                db.Pacients.Add(pacient);
                db.SaveChanges();
                return RedirectToAction("Index","Pacients");
            }

            ViewBag.MedicPId = new SelectList(db.Medics, "ID", "Nume", pacient.MedicPId);
            return View(pacient);
        }

        // GET: Pacients/Edit/5


        /// <summary>
        /// primeste id-ul de referinta a pacientului si editeaza informatiile despre pacient
        /// </summary>
        /// <param name="id"></param>
        /// <returns>string</returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacient pacient = db.Pacients.Find(id);
            if (pacient == null)
            {
                return HttpNotFound();
            }
            ViewBag.MedicPId = new SelectList(db.Medics, "ID", "Nume", pacient.MedicPId);
            return View(pacient);
        }

        // POST: Pacients/Edit/5
        /// <summary>
        /// facem un obiect de tip Pacient pentru a putea actualiza informatiile
        /// </summary>
        /// <param name="pacient"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nume,Prenume,Data,CNP,Email,Adresa,Telefon,NrCard,Asigurarea,Alergii,Antecedente_heredocolaterale,Antecedente_personale_patologice,Antecedente_personale_fiziologice,Meseria,LocMunca,Fumator,Elev,Student,Greutate,Sex,Varsta,DataNastere,MedicPId,Vaccinuri,Nr_sarcini,Nr_avorturi")] Pacient pacient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pacient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MedicPId = new SelectList(db.Medics, "ID", "Nume", pacient.MedicPId);
            return View(pacient);
        }

        // GET: Pacients/Delete
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacient pacient = db.Pacients.Find(id);
            if (pacient == null)
            {
                return HttpNotFound();
            }

            return View(pacient);
        }

        // POST: Pacients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pacient pacient = db.Pacients.Find(id);
            db.Pacients.Remove(pacient);
            db.SaveChanges();
            
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public int consultatieid;
        [HttpGet]
        public ActionResult AdaugaConsultatie(int consultatieid)
        {
            AdConsultatie model = new AdConsultatie();
            Consultatie consultatie = new Consultatie();
            if (Session["ID"] != null)
            {

                Pacient pacient = db.Pacients.Find(consultatieid);
                consultatie.PacientId = consultatieid;
                model.PacientId = consultatieid;
                model.MediCId = (int)Session["ID"];
                model.Data = DateTime.Now;
                return View("AdaugaConsultatie", model);
            }
            else
                return RedirectToAction("Conectare", "Inregistare");
        }

        /// <summary>
        /// creeam un obiect consultatie care deriva din clasa AdConsultatie
        /// creeam o variabila consultatieid in care stocam id-ul pacientului
        /// </summary>
        /// <param name="consultatie"></param>
        /// <param name="consultatieid"></param>
        /// <returns>string</returns>
        [HttpPost]
        public ActionResult AdaugaConsultatie(AdConsultatie consultatie,int consultatieid)
        {
            if (Session["ID"] != null)
            {
                Consultatie con = new Consultatie();
                Pacient pacient = db.Pacients.Find(consultatieid);
               // con.PacientId = consultatie.PacientId;
                con.PacientId = consultatieid;
                con.MediCId = (int)Session["ID"];
                con.Data = DateTime.Now;
                con.IMC=consultatie.IMC;
                con.Observatii = consultatie.Observatii;
                con.Temperatura = consultatie.Temperatura;
                con.Diagnostic = consultatie.Diagnostic;
                con.Greutate = consultatie.Greutate;
                con.Inaltime = consultatie.Inaltime;
                con.RezultateAnalize = consultatie.RezultateAnalize;
                con.Talie=consultatie.Talie;
                con.Tratament = consultatie.Tratament;


                db.Consultaties.Add(con);
                db.SaveChanges();
                return RedirectToAction("Index", "Pacients");
            }
            else
                return RedirectToAction("Inregistrare", "Conectare");


        }

    }
}

Doctor/Views/Pacients/Delete.cshtml
@model Doctor.Models.Pacient

@{
    ViewBag.Title = "Delete";
}

<h2>Esti sigur ca vrei sa stergi aceasta persoana!</h2>

<h3>Odata stearsa datele despre aceasta persoana se sterg definitiv</h3>
<div>
    @*<h4>Pacient</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CNP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NrCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NrCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Asigurarea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asigurarea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alergii)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alergii)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Antecedente_heredocolaterale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Antecedente_heredocolaterale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Antecedente_personale_patologice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Antecedente_personale_patologice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Antecedente_personale_fiziologice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Antecedente_personale_fiziologice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Meseria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Meseria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocMunca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocMunca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fumator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fumator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Elev)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Elev)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Greutate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Greutate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Varsta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Varsta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataNastere)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNastere)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vaccinuri)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vaccinuri)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nr_sarcini)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_sarcini)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nr_avorturi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nr_avorturi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medic.Nume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medic.Nume)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sterge" class="btn btn-danger" />
        </div>
        
            <div class="form-actions no-color">
                <a href="@Url.Action("Index", "Pacients")" class="btn btn-info">
                    Inapoi la pagina principala
                    <span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
                </a>
            </div>
            }
        </div>

Doctor/Views/Pacients/Index.cshtml
@model IEnumerable<Doctor.Models.Pacient>

@{
    ViewBag.Title = "Index";
}

<h2>Lista pacientilor</h2>
<p>
    @*@Html.ActionLink("Adauga un pacient nou", "Create")*@
    <a href="@Url.Action("Adaugare", "AdaugarePacient")" class="btn btn-success">
        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>
        Adauga un pacient nou

    </a>
</p>
<div class="search-box" style=" margin-bottom:10px">
    @using (Html.BeginForm("Index", "Pacients", FormMethod.Get))
    {
        @Html.TextBox("searching")<input type="submit" value="Search" />
    }
</div>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nume)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenume)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Data)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.CNP)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Adresa)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Telefon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NrCard)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Asigurarea)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.Alergii)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Antecedente_heredocolaterale)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Antecedente_personale_patologice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Antecedente_personale_fiziologice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Meseria)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LocMunca)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Fumator)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Elev)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Student)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Greutate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sex)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Varsta)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataNastere)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vaccinuri)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nr_sarcini)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nr_avorturi)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Medic.Nume)
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (item.MedicPId == (int)Session["ID"])
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prenume)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.CNP)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adresa)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Telefon)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NrCard)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Asigurarea)
                    </td>*@
                @*<td>
                        @Html.DisplayFor(modelItem => item.Alergii)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Antecedente_heredocolaterale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Antecedente_personale_patologice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Antecedente_personale_fiziologice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Meseria)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LocMunca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fumator)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Elev)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Student)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Greutate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sex)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Varsta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataNastere)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Vaccinuri)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nr_sarcini)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nr_avorturi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Medic.Nume)
                    </td>*@
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.ID })
                    </td>*@
                <td>
                    <a href="@Url.Action("Edit", "Pacients", new { id = item.ID })" class="btn btn-info">
                        <span class="glyphicon glyphicon glyphicon-edit" aria-hidden="true"></span>
                        Editeaza

                    </a>
                    @*<a href="@Url.Action("Delete", "Pacients", new { id = item.ID })" class="btn btn-danger">
                        <span class="glyphicon glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                        Sterge

                    </a>*@
                    <a href="@Url.Action("Details", "Pacients", new { id = item.ID })" class="btn btn-success">
                        <span class="glyphicon glyphicon glyphicon-list" aria-hidden="true"></span>
                        Detalii pacient

                    </a>
                    <a href="@Url.Action("AdaugaConsultatie", "Pacients", new { consultatieid = item.ID })" class="btn btn-warning">
                        <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
                        Adauga o consultatie

                    </a>
                    <a href="@Url.Action("Index1","Consultaties", new { consultatieid=item.ID })" class="btn btn-primary">
                        <span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span>
                        Consultatii

                    </a>

                </td>
            </tr>
            }
            

        }

    </table>